In [1]:
"""Creating a one dimensional array/vector"""
import numpy as np 
#create a row
array_row = np.array([1,2,3])
#create a column
array_col = np.array([[1],
                      [2],
                      [3]])
print (array_row)
print (array_col)

[1 2 3]
[[1]
 [2]
 [3]]


In [3]:
"""Creating a one two-dimensional array/matrix"""
import numpy as np
np_matrix = np.array([[1,2],
                   [3,4],
                   [5,6]])
print(np_matrix)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
"""Arrays are the de-facto data structure of numpy"""

In [4]:
"""Sparse matrices only store nonzero elements and assume all other values will be zero,
leading to significant computational savings"""
import numpy as np 
from scipy import sparse 
matrix = np.array([[0,0],
          [0,1],
          [3,0]])
#compressed sparced row (csr)
sparse_matrix = sparse.csr_matrix(matrix)
print(matrix),
print (sparse_matrix)

[[0 0]
 [0 1]
 [3 0]]
  (1, 1)	1
  (2, 0)	3


In [5]:
"""Creating a larger matrix"""
large_array = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
          [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
sparse_matrix = sparse.csr_matrix(large_array)
print(large_array)
print(sparse_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]
  (1, 1)	1
  (2, 0)	3


In [37]:
"""Selecting elements in a vector and matrix"""
import numpy as np 
np_vector = np.array([1, 2, 3, 4, 5, 6])
print(np_vector)
np_matrix = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(np_matrix)
# Select third element of vector
print(np_vector[2])
# Select second row, second column
print(np_matrix[1,1])
# Select all elements of a vector
print(np_vector[:])
# Select everything up to and including the third element
print(np_vector[:3])
# Select everything after the third element
print(np_vector[3:])
# Select the last element
print(np_vector[-1])
# Select the first two rows and all columns of a matrix
print(np_matrix[:2,:])
# Select all rows and the second column
print(np_matrix[:,1:2])


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


In [5]:
import numpy as np
matrix_1 = np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]])
matrix_1.shape
matrix_1.size
matrix_1.ndim

12