In [ ]:
"""To manipulate multiple elements in an array-vectorize an array"""

In [3]:
import numpy as np
matrix_1 = np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])
#create function that adds 100 to something 
add_100 = lambda i: i+100
"""vectorize function = It’s worth noting that vectorize is essentially a
for loop over the elements and does not increase performance."""
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(array_1)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [8]:
"""Finding max and min of an array"""
import numpy as np 
matrix_1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
np.max(matrix_1), np.min(matrix_1)

# Find maximum element in each column
np.max(matrix_1, axis=0),np.min(matrix_1, axis=1)

(array([7, 8, 9]), array([1, 4, 7]))

In [12]:
"""Calculate matrix's mean, variance and standard deviation"""
import numpy as np 
matrix_1 = np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])
#return the mean 
np.mean(matrix_1)
#return variance
np.var(matrix_1)
#standard deviation 
np.std(matrix_1)
#you can also find the mean for an axis instead of a matrix
np.mean(matrix_1, 0)

array([4., 5., 6.])

In [23]:
"""You want to change the shape (number of rows and columns) of an array without
changing the element values."""
import numpy as np 
matrix_1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]])
"""Reshape matrix from 4x6 into 2x6 matrix without changing elements"""

matrix_1.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])